### PR TITLE
added file

### PR DESCRIPTION
**Pull request by KaylaReid**
check this out please @Akeen11 @gretchenmarie I added the insert statements to the SQL file and made a models folder for us to put out models in

### CODE REVIEW

**Review by Akeen11 — APPROVED** [review]
💯

**Review by gretchenmarie — APPROVED** [review]
looks good

**Review by askingalot — CHANGES_REQUESTED** [review]
Please follow the PR template.

https://github.com/spooky-oysters/bangazon-web-app/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by KaylaReid** [comment]
to test try running SQL Statement to create db tables and seed the db.

**Review by askingalot — APPROVED** [review]
This PR still doesn't really match the template, but I'm feeling nice (this time) so I'm going to approve it. Please follow the template in the future.

**Pull request merged**
